---
apiVersion: v1
kind: Namespace
metadata:
  name: service4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service4
  namespace: service4
spec:
  selector:
    matchLabels:
      app: service4
  replicas: 1
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
        - name: service4
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service4
  namespace: service4
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service4
