---
apiVersion: v1
kind: Namespace
metadata:
  name: service2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  namespace: service2
spec:
  selector:
    matchLabels:
      app: service2
  replicas: 1
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
        - name: service2
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: service2
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service2
