---
apiVersion: v1
kind: Namespace
metadata:
  name: service1
#---
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: nginx-conf
#data:
#  nginx.conf: |
#    user nginx;
#    worker_processes  1;
#    events {
#      worker_connections  10240;
#    }
#    http {
#      server {
#          listen       80;
#          server_name  localhost;
#          location / {
#            root   /usr/share/nginx/html; #Change this line
#            index  index.html index.htm;
#        }
#      }
#    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: service1
spec:
  selector:
    matchLabels:
      app: service1
  replicas: 1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: nginx
          ports:
            - containerPort: 80
#          volumeMounts:
#            - name: service1
#              mountPath: /etc/nginx/nginx.conf
#              subPath: nginx.conf
#              readOnly: true
#      volumes:
#        - name: service1
#          configMap:
#            name: service1
#            items:
#              - key: nginx.conf
#                path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: service1
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service1
