---
apiVersion: v1
kind: Namespace
metadata:
  name: service3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service3
  namespace: service3
spec:
  selector:
    matchLabels:
      app: service3
  replicas: 1
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
        - name: service3
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service3
  namespace: service3
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service3
