---
apiVersion: v1
kind: Namespace
metadata:
  name: service5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service5
  namespace: service5
spec:
  selector:
    matchLabels:
      app: service5
  replicas: 1
  template:
    metadata:
      labels:
        app: service5
    spec:
      containers:
        - name: service5
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service5
  namespace: service5
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service5
